### ISSUE TITLE
Containerize guide with Podman

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#744] opened 2021-10-22 19:47 UTC
Create a new guide as similar as the containerize guide but use Podman instead.

**Comment by gkwan-ibm** [comment] 2021-10-22 19:49
@davidwyao drafted at https://github.com/davidwyao/guide-podman/tree/podman-update

**Comment by gkwan-ibm** [comment] 2021-10-22 19:50
hi @davidwyao, I reviewed your draft, following is my initial comments:

- [x] rename the guide project id and repo to containerize-podman
- **What you’ll learn**
  - [x] "...using Podman for your microservices." -> "...using the Pod Manager tool (Podman) for your microservices."
    - and Add the link `https://docs.podman.io` to the words "Pod Manager tool"
  - [x] "You’ll construct `Dockerfile` files,..." -> "You’ll construct Containerfile files,..."
- **Additional prerequisites**
  - [x] "...in Podman containers." -> "...in containers." ->
  - why removed the statement "Make sure to start your Docker daemon before you proceed."? 
    - for Mac, at least "Make sure to start your Podman-managed VM before you proceed."
    - for Linux and Win, find out what is required to start
- **Building your Podman images**
  - [x] rename the section title to "Building your container images"
  - [x] "Podman image" -> "container image" for the whole guide
  - [x] "Podman container" -> "container" for the whole guide
  - [x] Dockerfiles -> Containerfiles for the whole guide
  - [x] "Podman layer" -> a better industrial name in the whole guide
- **Creating your Dockerfiles**
  - [x] rename the subsection title to "Creating your Containerfiles"
  - [ ] rewrite the paragraph "In this case, ...."
    - not use Dockerhub
    - need to find out a doc that list all OL images are available at icr.io/appcafe
  - [ ] search any doc for Containerfiles that can replace "Best practices for writing Dockerfiles."
- avoid using Docker or Dockerhub or DockerDesktop if possible

**Comment by gkwan-ibm** [comment] 2021-10-26 20:18
- **Creating your Containerfiles**
  - [x] remove the statement "For more information, see Best practices for writing Containerfiles."
- **Building your container image**
  - [x] update the output at the bottom for the values under the REPOSITORY and SIZE
- **Running your microservices in containers**
  - [x] update the output for the values under the IMAGE and COMMAND
  - [x] `172.17.0.2` to `10.88.0.2`

**Comment by gkwan-ibm** [comment] 2021-10-27 14:31
- **Creating your Containerfiles**
  - [x] "In this case, you’re using the recommended production image,..." -> "In this case, you’re using the recommended production image from the IBM container registry, ..." 
  - [x] `FROM open-liberty:kernel-slim` -> `FROM icr.io/appcafe/open-liberty:kernel-java11-openj9-ubi` 
- **Running your microservices in containers**
  - [x] ` 172.17.0.2` to `10.88.0.2`
    - fixed one but missed another

**Comment by gkwan-ibm** [comment] 2021-10-28 16:18
- **Creating your Containerfiles**
  - [x] "...instruction as `FROM open-liberty`."  -> "...instruction as `FROM icr.io/appcafe/open-liberty`."

**Comment by yeekangc** [comment] 2021-11-01 16:25
This is a duplicate of https://github.com/OpenLiberty/guides-common/issues/731?

**Comment by yeekangc** [comment] 2021-11-04 21:18
https://github.com/OpenLiberty/ci.maven/issues/1278 calls for devc's enhancement to support podman.  For future updates/work but noting it here for now.

**Comment by yeekangc** [comment] 2022-03-04 21:51
Let us proceed to publish this guide.  Thank you, @priyyanshi @gkwan-ibm!

**Comment by yeekangc** [comment] 2022-03-10 16:43
https://openliberty.io/guides/containerize-podman.html published.

**Closed as completed by yeekangc** 2022-03-10 16:43 UTC
Labels: ID reviewed, new guide, static, peer reviewed, dev content reviewed, SME reviewed, user reviewed, final end-to-end test completed, signed off, final content reviewed
