### ISSUE TITLE
Create a solution to get the prereqs ready for the guides

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#228] opened 2019-02-07 16:21 UTC
As feedback from workshops where students are trying the guides as a hands-on lab, lots of them got stuck or spend lots of time getting the prereqs ready before they go to the guide. 

 Pre-requisites
To use this lab you need the following pre-requisites:
1. Java 8 JDK
(e.g. https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=openj9)
2. Apache Maven (https://maven.apache.org/)
3. Git client
4. Editor with Java support (e.g. Atom, Eclipse, VS Code, IntelliJ)
5. Docker (Optional - not required for the guides in this tutorial but used in other guides you may wish to try afterwards)

**Comment by yeekangc** [comment] 2019-02-07 16:27
This is a duplicate of the Docker item to simplify setup for Quick Labs and/or an issue against or update to the tutorial repo i.e. OpenLiberty/microprofile-tutorial.

**Comment by gkwan-ibm** [comment] 2020-11-25 21:16
close
- cloud hosted guides will be implemented to address this issue

**Closed by gkwan-ibm** 2020-11-25 21:16 UTC
Labels: wontfix
