### ISSUE TITLE
Provide setup local dev site instruction for contributor

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#241] opened 2019-03-11 19:00 UTC
For the instruction Step 4.2, should we point contributor to the setup local dev site wiki to develop readme? https://github.com/OpenLiberty/openliberty.io/wiki/Setting-up-local-website-development

Note, the link above need some work to make it targeted for setting the dev site environment for guides.

**Comment by yeekangc** [comment] 2019-03-14 15:45
Related to https://github.com/OpenLiberty/guides-common/issues/207.  May be a duplicate of each other?

**Comment by gkwan-ibm** [comment] 2020-11-25 21:19
close
- duplicate of #207

**Closed by gkwan-ibm** 2020-11-25 21:19 UTC
Labels: duplicate
