### ISSUE TITLE
Update guides for new OS-specific support

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#288] opened 2019-06-05 17:49 UTC
Make sure the following guides to use the new OS-specific support  
- [x]  guide-docker
- [x]  guide-kubernetes-intro
- [x]  guide-kubernetes-microprofile-health
- [x]  guide-kubernetes-microprofile-config
- [x]  guide-istio-intro
    - need to address https://github.com/openliberty/guide-istio-intro/issues/66 as well
- [x]  guide-cloud-aws
- [x] guide-cloud-ibm

**Comment by gkwan-ibm** [comment] 2019-06-05 17:52
May see https://github.com/OpenLiberty/guides-common/pull/286 how to make  change

**Comment by gkwan-ibm** [comment] 2019-06-05 18:25
- let create branch `os-specific`
- try to convert the istio guide first to flush out any issues
- use lgdev to see how the changes look

**Comment by DannyS03** [comment] 2019-06-06 20:32
Update for guide-istio-intro

![image](https://user-images.githubusercontent.com/25497083/59064513-6d236500-8878-11e9-893d-fbc237dcb460.png)

**Comment by DannyS03** [comment] 2019-06-07 17:49
Need to modify generic adoc files that are used across the guides
- kube-prereq.adoc
- kube-start.adoc
- kube-minikube-teardown.adoc

**Comment by DannyS03** [comment] 2019-06-18 20:27
Better labels 

![image.png](https://images.zenhubusercontent.com/5ce832dc02fc877f41d24e21/db9e367d-d786-4c1b-9d1c-a3ce28b60f7f)

**Comment by DannyS03** [comment] 2019-06-19 15:20
- istio guide os-specific commands all updated 
- Should find a better way to show the tab for their os-specific command rather than having the user press it each time

**Comment by evelinec** [comment] 2019-06-24 14:51
- Steven is working on the design for the Istio guide

**Comment by DannyS03** [comment] 2019-06-25 14:45
- Steven opened issue to modify front-end to support more than one set of tabs on the guide

**Comment by DannyS03** [comment] 2019-06-26 17:36
- More than one set of tabs now supported 
- All guides with os-specific commands updated on `os-specific` branch 
- Changes verified on `lgdev` site

**Comment by DannyS03** [comment] 2019-06-28 14:35
https://github.com/OpenLiberty/openliberty.io/issues/1096#issuecomment-506006491

**Comment by ellenwyllie** [comment] 2019-07-03 19:18
@DannyS03 On the docker guide in the second set of os specific instructions under #containerize-your-application, the windows and mac blocks look different than the linux one. 

![Screen Shot 2019-07-03 at 2 15 04 PM](https://user-images.githubusercontent.com/22085207/60618907-0b81e800-9d9d-11e9-8cd8-184fcab1b1fe.png)

It looks like they are missing `[role='command']` in the adoc

**Comment by DannyS03** [comment] 2019-07-03 19:50
> @DannyS03 On the docker guide in the second set of os specific instructions under #containerize-your-application, the windows and mac blocks look different than the linux one.
> 
> ![Screen Shot 2019-07-03 at 2 15 04 PM](https://user-images.githubusercontent.com/22085207/60618907-0b81e800-9d9d-11e9-8cd8-184fcab1b1fe.png)
> 
> It looks like they are missing `[role='command']` in the adoc

Fixed! Thanks for pointing it out.

**Comment by DannyS03** [comment] 2019-07-09 19:00
- guide-istio-intro updated with optimized implementation 
``` 
[.tab_link.windows_link]
`*WINDOWS*`
[.tab_link.mac_link]
`*MAC*`
[.tab_link.linux_link]
`*LINUX*`
```

```
[.tab_content.windows_section.mac_section]
---
... same instruction for Windows and Mac ...
---
[.tab_content.linux_section]
---
...
---
```

Guides to update 
- [ ] guide-docker
- [ ] guide-kubernetes-intro
- [ ] guide-kubernetes-microprofile-health
- [ ] guide-kubernetes-microprofile-config
- [ ] guide-cloud-aws
- [ ] guide-cloud-ibm

**Comment by DannyS03** [comment] 2019-07-09 19:02
- UI updated to indent tab content 

![image.png](https://images.zenhubusercontent.com/5ce832dc02fc877f41d24e21/bda7b391-6ec3-4e8c-be35-19f5c57ea20b)

**Comment by DannyS03** [comment] 2019-07-09 19:28
- [ ] Verifying changes on lgdev site 
- [ ] Review/feedback during weekly team demo

**Comment by DannyS03** [comment] 2019-07-10 13:57
@ellenwyllie for the ibm cloud guide, when clicking the os tabs under the preq section, the tabs just get highlighted and one cannot view the content. This is the case when there is an indent `+` in place in the README.adoc, like how it was originally. 

![image.png](https://images.zenhubusercontent.com/5ce832dc02fc877f41d24e21/605cb567-567b-44f2-a7ee-9a22729cf583)

![image.png](https://images.zenhubusercontent.com/5ce832dc02fc877f41d24e21/4501dcf4-9a51-4a71-8cb5-b0e3a8695528)

**Comment by ellenwyllie** [comment] 2019-07-11 15:04
@DannyS03 I'm working on a fix for the issue you're talking about on the ibm cloud guide.

**Comment by DannyS03** [comment] 2019-07-11 15:45
> @ellenwyllie for the ibm cloud guide, when clicking the os tabs under the preq section, the tabs just get highlighted and one cannot view the content. This is the case when there is an indent `+` in place in the README.adoc, like how it was originally.
> 
> ![image.png](https://camo.githubusercontent.com/38a959ac3141284638fadeaefe85929c2b87a428/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563653833326463303266633837376634316432346532312f36303563623536372d353637622d343466322d613765652d396132323732396366353833)
> 
> ![image.png](https://camo.githubusercontent.com/dd6a06293b56f1ff0773cc58375677402c2617c1/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3563653833326463303266633837376634316432346532312f34353031646366342d396135312d346137312d386362352d623065336138363935353238)

guide-kubernetes-microprofile-config 

![image](https://user-images.githubusercontent.com/25497083/61065280-5ae59b00-a3d1-11e9-9c75-4d6b234b407c.png)

**Comment by DannyS03** [comment] 2019-07-11 19:46
@ellenwyllie sorry also for the Istio guide the repetitive sections on the side come up due to the doc syntax change.

`Nice work! You're Done!`
`Nice work! Where to next?`

I was told it was an issue previously with this guide 

![image](https://user-images.githubusercontent.com/25497083/61080444-123ed980-a3f3-11e9-95d0-0f8f36e0075b.png)

**Comment by DannyS03** [comment] 2019-07-11 19:47
> @DannyS03 I'm working on a fix for the issue you're talking about on the ibm cloud guide.

Thanks!

**Comment by ellenwyllie** [comment] 2019-07-15 16:03
@DannyS03 For your comment about the repetitive sections in the istio guide, it looks like that change was caused by this wording change:

![Screen Shot 2019-07-15 at 10 58 02 AM](https://user-images.githubusercontent.com/22085207/61230343-7b726580-a6ef-11e9-8438-d634d9eb2214.png)

I'm not sure if that has anything to do with the os tabs.

**Comment by evelinec** [comment] 2019-07-16 15:16
- addressing the review feedback

**Comment by DannyS03** [comment] 2019-07-23 13:47
@ellenwyllie Is there a way for the auto-detection for the tabs to work so that when the user clicks an os-specific tab, all the other tabs in the guide change respectively, rather than the user having to click on that os tab every single time?

**Comment by ellenwyllie** [comment] 2019-07-23 15:45
@DannyS03 Yes, I can do that. I'm working on a pr for that now.

 I just noticed that in the docker guide, the closing bracket is missing on line 308 
<img width="394" alt="Screen Shot 2019-07-23 at 10 43 19 AM" src="https://user-images.githubusercontent.com/22085207/61726193-dd0d8200-ad36-11e9-9f80-0f31c21d17a7.png">

**Comment by evelinec** [comment] 2019-07-30 14:51
- all the PRs are ready, pending on review in the `ready to qa` pipeline (admin is needed)

**Comment by DannyS03** [comment] 2019-09-19 14:07
- `guide-cloud-openshift` and `guide-microprofile-istio-retry-fallback` guides both converted and under review - applying feedback. 
- Need to convert `Tearing down the environment` for `guide-sessions` guide 

- Other newly published guides do not have os-specific commands. 

Target: Today

**Comment by DannyS03** [comment] 2019-09-24 17:36
- PR's for new guides all ready to be verified in qa

- According to https://github.com/OpenLiberty/guides-common/issues/344
may need to change `include` command for common adoc files in guides-common repo to absolute path

**Closed** 2019-09-26 14:39 UTC
Labels: enhancement, good first issue, static
