### ISSUE TITLE
Create a guide for validating form input

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#33] opened 2018-01-05 21:00 UTC
Guide on validating form input or data (using bean validation).

**Comment by yeekangc** [comment] 2018-03-09 16:12
Need to reconcile with #8.

**Comment by yeekangc** [comment] 2018-05-24 14:17
This is a duplicate of what we have for Bean Validation in #8.  Closing.

**Closed by yeekangc** 2018-05-24 14:17 UTC
Labels: new guide
