### ISSUE TITLE
Create a guide for building Dual Layer Docker images for Spring Boot apps

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/guides-common#144] opened 2018-07-03 15:12 UTC
Create a guide for creating Docker images for Spring Boot applications. This is based on the blog posts:
[Optimizing Spring Boot apps for Docker](https://openliberty.io/blog/2018/06/29/optimizing-spring-boot-apps-for-docker.html)
[Creating Dual Layer Docker images for Spring Boot apps](https://openliberty.io/blog/2018/07/02/creating-dual-layer-docker-images-for-spring-boot-apps.html)

*Before* the guide is created, there is some work to improve the usability. Docker images are also not yet published.

**Comment by yeekangc** [comment] 2018-07-04 21:13
This is a duplicate of #79.  Closing this and we will track using #79.

**Closed** 2018-07-04 21:13 UTC
Labels: new guide
