### ISSUE TITLE
Create a guide how to use Kafka 

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#380] opened 2019-12-13 17:44 UTC
Explain how to use Kafka APIs KafkaProducer and  KafkaConsumer to generate and consume messages in a microservices application

**Comment by evelinec** [comment] 2019-12-16 15:40
- creating repo
- draft and content is ready to push to repo
- dev content review can start

**Comment by jonathanxue** [comment] 2019-12-16 20:11
https://github.com/OpenLiberty/draft-guide-kafka-intro/tree/dev

Repo created here

**Comment by gkwan-ibm** [comment] 2019-12-18 15:39
- need dev content review

**Comment by gkwan-ibm** [comment] 2019-12-20 15:41
- dev content review in progress

**Comment by yeekangc** [comment] 2020-01-21 17:22
This is a duplicate of an existing issue?

**Comment by yeekangc** [comment] 2020-12-11 21:24
This is now superseded by the series of guides on MP Reactive Messaging.

**Closed by yeekangc** 2020-12-11 21:24 UTC
Labels: new guide, static
