### ISSUE TITLE
Guide for Spring Boot

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/guides-common#79] opened 2018-02-27 17:12 UTC
This relates to the Spring Boot support in Open Liberty.

**Comment by yeekangc** [comment] 2018-06-19 18:27
@tjwatson, FYI that @uberskigeek @awisniew90 will be taking a look at this guide.

**Comment by yeekangc** [comment] 2018-06-26 18:06
@uberskigeek @awisniew90, feel free to post an outline when ready so we can look and iterate on it if necessary.  Thank you.

**Comment by awisniew90** [comment] 2018-07-02 20:50
@yeekangc - here is our repo with draft content if you'd like to take a look: https://github.com/OpenLiberty/draft-guide-spring-boot

**Comment by yeekangc** [comment] 2018-07-04 21:18
@uberskigeek @awisniew90, @barecode created #144, which is a duplicate of this issue that is in progress, and provided the below:

_Create a guide for creating Docker images for Spring Boot applications. This is based on the blog posts:
[Optimizing Spring Boot apps for Docker](https://openliberty.io/blog/2018/06/29/optimizing-spring-boot-apps-for-docker.html)
[Creating Dual Layer Docker images for Spring Boot apps](https://openliberty.io/blog/2018/07/02/creating-dual-layer-docker-images-for-spring-boot-apps.html)

Before the guide is created, there is some work to improve the usability. Docker images are also not yet published._

Please consider the above.

@barecode @tjwatson, please feel free to chime in and/or contribute to what Adam and Mike are working on here.

**Comment by yeekangc** [comment] 2018-09-27 15:19
We believe Boost is the path forward.  We will take what we have here and incorporate what is relevant and necessary into #175 that will focus on developing Spring Boot apps with Boost.

Thank you for everybody's contributions!

**Closed by yeekangc** 2018-09-27 15:19 UTC
Labels: new guide, superseded

**Comment by yeekangc** [comment] 2018-09-27 15:28
@kinueng, my initial thought was to archive such repos if possible.  Haven't looked into how it can or should be done.  Your input welcome.
