### ISSUE TITLE
Problem with servers being left around.

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/guides-common#157] opened 2018-07-30 13:20 UTC
I went to London on Saturday to host a workshop with the London Java Community. The workshop was on MicroProfile and Open Liberty and the attendees went through some of the Open Liberty guides. 

I noticed that most of the attendees were not capable of finishing multiple guides without our help which I found was due to a common problem that kept occurring. 

When using the guides people kept having an error: "unable to bind to port 9080". This was a result of having the server still running from either a previous guide or from testing out the project at the beginning of the guide. We need to fix this as I am well aware of this message but non WAS users are not so they get stuck and will give up if no additional help is provided. I am suggesting a troubleshooting section that will show fixes for these common problems rather than not mention them at all or provide better error messages.

**Comment by yeekangc** [comment] 2018-08-06 08:56
@gkwan-ibm @evelinec, can you please follow up?

**Comment by evelinec** [comment] 2018-08-08 19:12
Most of our guides do have instructions at the end of each liberty server start command to stop the server, which would not cause the problem as described. There's one guide I found that may have this missing, which we can fix (issue created). I think we'd raise this issue to OL for a better message instead of a troubleshooting section on the guides.

**Comment by gkwan-ibm** [comment] 2018-08-08 21:11
"unable to bind to port 9080" can be caused by running Liberty, but it can be caused by running tWAS or other application. Should ask user to stop any running application which are using that port or change the ports at server.xml

**Comment by evelinec** [comment] 2018-08-10 18:47
@gkwan-ibm we know about the cause and resolution, but this is now a serviceability/usability issue that I think we'd fix the message. What do you think? Thanks.

**Comment by gkwan-ibm** [comment] 2018-08-10 20:44
My 2 cents: A message may not be enough. When users encounter any problem in setting / running a guide, they may want to know what next or how to fix. In long term, we should have a common troubling guide or wiki page at somewhere, so that all guides can point to it.

**Comment by evelinec** [comment] 2018-08-13 19:36
@gkwan-ibm I meant to say we'd have the message fixed in OL.

**Comment by kathrynkodama** [comment] 2018-12-31 15:34
I was working through the MicroProfile guides and ran into a similar error.  At the end of this guide: https://openliberty.io/guides/rest-intro.html
There are no instructions to execute `mvn liberty:stop-server`. When I moved on to the next guide I forgot to stop the server and my future `mvn install` commands were blocked until I realized and manually killed the java processes.

**Comment by gkwan-ibm** [comment] 2023-02-10 15:15
close
- the problem should be addressed by https://github.com/OpenLiberty/ci.maven/issues/850

**Closed by gkwan-ibm** 2023-02-10 15:15 UTC
Labels: static
