### ISSUE TITLE
Support for Java 11

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guides-common#193] opened 2018-10-15 14:24 UTC
We need to ensure that the guides work with Java 11.  This should be more a testing effort since we have handled what's needed with removed APIs when we added support for Java 9 and 10.

**Comment by gkwan-ibm** [comment] 2019-01-16 22:10
- make sure daily auto test cover OpenJDK11
- run a set of guides by using HotSpot JDK 11 and OpenJDK11 in following platforms
  - Windows
  - Ubanto
  - Macs???
  - Linux

**Comment by evelinec** [comment] 2019-01-21 15:46
- will sort the version for the jdk9+ dependencies and open PR for master branch on the failed guides

**Comment by evelinec** [comment] 2019-01-23 15:48
- gradle v5
  - hotspot test is good
  - openj9 test failed at opening the browser step, investigating
- kube guides
  - PRs are merged, checking test results on travis
  - tests with both hotspot and openj9 are good on Andrew's environment
  - openj9 failed on Justine's environment for Kube+health, investigating

**Comment by evelinec** [comment] 2019-01-24 15:47
- gradle v5: 
  - openj9 test was ok with linux; still have issue on mac (with `sudo gradle build` was good) 
- kube guides
  - all tests passed

**Comment by evelinec** [comment] 2019-01-25 15:49
- gradle v5: 
  - cannot reproduce the sudo problem after refresh environment
  - tested overwriting the gradle v5 install on travis.yml and it's working, open PR for master

**Comment by evelinec** [comment] 2019-01-28 15:55
- gradle v5: 
  - PR is ready

**Comment by evelinec** [comment] 2019-01-30 15:49
- @andrewdes to list the manual test coverage here

**Comment by andrewdes** [comment] 2019-01-30 16:27
- [ ] Getting-started (Hotspot JDK11, Ubuntu)
- [ ] JWT (Hotspot JDK11, Windows)
- [ ] Kubernetes-intro (OpenJDK11, Windows & Linux ReHatx86)
- [ ] Gradle (OpenJDK11, MacOS)
- [ ] Rest-client-java (OpenJDK 11, MacOS)
- [ ] JPA-intro (Hotspot JDK11, Ubuntu)

- [ ] Kubernetes-intro (OpenJDK11, MacOS & Ubuntu)
- [ ] Kubernetes-health (OpenJDK11, MacOS & Ubuntu)
- [ ] Kubernetes-config (OpenJDK11, MacOS & Ubuntu)

**Comment by evelinec** [comment] 2019-02-01 19:39
Team discussed to do more manual test for the following combination: 

- [ ] Kube-health (Redhat, OpenJDK11, OL19001, Docker image 18004 with JDK8)

- [ ] Kube-config (Windows, OpenJDK11, OL19001, Docker image 18004 with JDK8)

**Comment by evelinec** [comment] 2019-02-04 16:08
- [ ] OpenJDK11 OpenJ9 fails with "too many file opened" compilation error for the guides on Mac

**Comment by gkwan-ibm** [comment] 2019-02-05 15:41
- The getting start guide got warnings in Java11, OL 18003
  - investigating an issue on Win

**Comment by gkwan-ibm** [comment] 2019-02-12 16:12
- [ ] gradle guide may fail by Java11 OpenJ9
   - Andrew cannot reproduce
   - Gilbert will retry
   - require Gradle 5+

**Closed** 2019-02-13 15:41 UTC
Labels: enhancement, static
