### ISSUE TITLE
Make sure the start directory is same as the finish directory

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guides-common#202] opened 2018-11-23 18:45 UTC
When create PR, currently, most of the guides will run `mvn install` under the finish directory by Travis. This issue will implement a way to guarantee the start directory is same as the finish directory during PR testing, instead of finding out-of-sync very late by manually check.

**Comment by yeekangc** [comment] 2020-11-25 15:42
This looks to be a duplicate of #532?

**Comment by yeekangc** [comment] 2020-11-25 15:43
Closing as a duplicate.  If this is still needed, we can re-open when necessary.

**Closed by yeekangc** 2020-11-25 15:43 UTC
Labels: duplicate, static
